services:
  # Solicitud
  ## Db solicitud
  db_solicitud:
    image: mysql:5.7
    restart: always
    ports:
      - "3019:3306"
    expose:
      - "3019"
    volumes:
      - "./sql/solicitud:/docker-entrypoint-initdb.d"
    env_file:
      - ./Solicitud/process.env
    networks:
      - emprenred
    container_name: db_solicitud
  ## Microservicio solicitud
  solicitud:
    tty: true
    build: ./Solicitud/.
    container_name: solicitud
    ports:
      - "3009:3009"
    expose:
      - "3009"
    links:
      - db_solicitud
    depends_on:
      - db_solicitud
    command: node src/index.js
    env_file:
      - ./Solicitud/process.env
    volumes:
      - "./Solicitud:/Backend"
    networks:
      - emprenred

  # Experto
  ## Db experto
  db_experto:
    image: mysql:5.7
    restart: always
    ports:
      - "3018:3306"
    expose:
      - "3018"
    volumes:
      - "./sql/experto:/docker-entrypoint-initdb.d"
    env_file:
      - ./Experto/process.env
    networks:
      - emprenred
    container_name: db_experto
  ## Microservicio experto
  experto:
    tty: true
    build: ./Experto/.
    container_name: experto
    ports:
      - "3008:3008"
    expose:
      - "3008"
    links:
      - db_experto
    depends_on:
      - db_experto
    command: node src/index.js
    env_file:
      - ./Experto/process.env
    volumes:
      - "./Experto:/Backend"
    networks:
      - emprenred

  # Micronegocio
  ## Db micronegocio
  db_micronegocio:
    image: mysql:5.7
    restart: always
    ports:
      - "3017:3306"
    expose:
      - "3017"
    volumes:
      - "./sql/micronegocio:/docker-entrypoint-initdb.d"
    env_file:
      - ./Micronegocio/process.env
    networks:
      - emprenred
    container_name: db_micronegocio
  ## Microservicio experto
  micronegocio:
    tty: true
    build: ./Micronegocio/.
    container_name: micronegocio
    ports:
      - "3007:3007"
    expose:
      - "3007"
    links:
      - db_micronegocio
    depends_on:
      - db_micronegocio
    command: node src/index.js
    env_file:
      - ./Micronegocio/process.env
    volumes:
      - "./Micronegocio:/Backend"
    networks:
      - emprenred

  #Haproxy
  haproxy:
    build: ./haproxy
    links:
      - web1
      - web2
    ports:
      - "5080:80"

  web1:
    build: ./Frontend
    volumes:
      - ./Frontend/html1:/var/www/html/

  web2:
    build: ./Frontend
    volumes:
      - ./Frontend/html2:/var/www/html/
networks:
  emprenred: